version: '3'
services:
  kvs:
    image: hazelcast/hazelcast:3.12.6
    environment:
      JAVA_OPTS: -Dhazelcast.local.publicAddress=0.0.0.0:5701
    ports:
      - "5701:5701"
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: bouncr
      POSTGRES_USER: bouncr
    ports:
      - "5432:5432"

  proxy:
    image: bouncr/bouncr-proxy
    depends_on:
      - db
      - kvs
      - api
    environment:
      PORT: "3000"
      JDBC_URL: jdbc:postgresql://db:5432/bouncr
      JDBC_USER: bouncr
      JDBC_PASSWORD: bouncr
      JAVA_OPTS: -Dhazelcast.member.address=kvs
    ports:
      - "3000:3000"

  api:
    image: bouncr/bouncr-api-server
    depends_on:
      - db
      - kvs
    environment:
      PORT: "3005"
      JDBC_URL: jdbc:postgresql://db:5432/bouncr
      JDBC_USER: bouncr
      JDBC_PASSWORD: bouncr
      JAVA_OPTS: -Dhazelcast.member.address=kvs -Dorg.slf4j.simpleLogger.defaultLogLevel=DEBUG
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
      - "3005:3005"
      - "5005:5005"
