openapi: 3.0.0
info:
  version: 0.2.0
  title: Bouncr API Specification
  license:
    name: EPL 2.0
paths:
  /users:
    get:
      parameters:
      - in: query
        name: limit
        schema:
          type: number
      - in: query
        name: offset
        schema:
          type: number
      responses:
        200:
          description: ???
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
  /user/{account}:
    parameters:
    - name: account
      in: path
      schema:
        type: string
    get:
      responses:
        200:
          description: ???
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    put:
      responses:
        204:
          description: Updated a user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConstraintsProblem'
    delete:
      responses:
        204:
          description: Delete a user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    Users:
      type: array
      items:
        $ref: '#/components/schemas/User'
    User:
      type: object
      properties:
        account:
          type: string
        name:
          type: string
        email:
          type: string
    ConstraintsProblem:
      type: object
      properties:
        violations:
          type: array
          items:
            schema:
              $ref: '#/components/schemas/ConstraintsViolation'
    ConstraintsViolation:
      type: object
      properties:
        name:
          type: string
        value:
          type: string


